### ISSUE TITLE
Battery status does not get saved

### ISSUE THREAD

**Issue by OverloadUT** [wpietri/sucks#12]
I assume this is meant to assign to `self.battery_status`:

https://github.com/wpietri/sucks/blob/master/sucks/__init__.py#L173

**Comment by wpietri** [comment]
Ah, just saw this. For what it's worth, I was intentionally not saving battery status. I had a handler there because if you don't handle messages, you get errors. But unlike the other two handlers, the battery status wasn't getting used for anything other than a debug message, so there was no need to keep it.

I'm glad to put it there as an experiment in figuring out how this object gets used in situations like yours.
