### ISSUE TITLE
Warning: "resource property deprecated. Use boundjid.resource"

### ISSUE THREAD

**Issue by joe248** [wpietri/sucks#46]
Using the Ecovacs component in Home Assistant 0.77 and seeing this in the logs constantly:

`WARNING (SyncWorker_12) [sleekxmpp.basexmpp] resource property deprecated.       Use boundjid.resource`

**Comment by joe248** [comment]
I also see this but only at startup, so it's not as annoying:

`WARNING (SyncWorker_12) [sleekxmpp.basexmpp] fulljid property deprecated.       Use boundjid.resource`

I'm not sure how to fix this one as I don't see "fulljid" anywhere in the code.

**Comment by wpietri** [comment]
Thanks for fixing this! I appreciate it.

**Comment by joe248** [comment]
No problem.  Thanks for this library!

**Comment by rchamp26** [comment]
i am running the latest home assistant version 0.95.4 and the ecovacs vacuum now works again, but i continue to get this same warning

fulljid property deprecated. Use boundjid.resource

**Comment by jumate** [comment]
Same problem, with home assistant version 0.102.3

**Comment by bggardner** [comment]
This is caused by the `sleekxmppfs.basexmpp` module, for which there is no GitHub repo (that I could find).  If you comment out line 610 of `sleekxmppfs/basexmpp.py`, the warning will be suppressed.  The location of the file will vary based on your installation.

@wpietri - I believe the warning should say "resource property deprecated..."  Correspondingly, the use of `self.resource` in this repo should use `self.boundjid.resource` instead.  I may do a pull request.
