### ISSUE TITLE
Run until battery low?

### ISSUE THREAD

**Issue by MABeatty1978** [wpietri/sucks#59]
I could probably just try it out and see what happens, but if I want the vac to just run as long as it can and then return to the base like it normally would in "Auto" mode, can I just set a large number for the clean time and it'll just do its thing and come back without affecting the script?

Say I do, sucks clean 240.  Will it clean then return to the base on its own when the battery dies?  Will this have any kind of negative impact?  Will the script end on its own?

**Comment by wpietri** [comment]
Hi! I believe that will work. My guess is that the robot will eventually go charge on its own during the clean period. When the time limit expires, sucks will then tell the robot to go charge. But since it's charging, I expect the script will just end. If you encounter problems you might instead try "sucks clean 240 stop", which instead of sending a charge command at the end will send a stop command.
